project:
  type: website

website:
  title: "Specflow is structure for building with software agents"
  description: "Use the open Specflow method to turn intent into software through structured planning and iterative execution with software agents."
  site-url: "https://www.specflow.com"
  favicon: "assets/favicon.ico"
  search:
    location: navbar
    type: overlay
    copy-button: true
  open-graph:
    title: "Specflow - Structure for Building with AI Agents"
    description: "Use the open Specflow method to turn intent into software through structured planning and iterative execution with software agents."
    image: "https://www.specflow.com/assets/og-image.png"
    site-name: "Specflow"
  twitter-card:
    title: "Specflow - Structure for Building with AI Agents"
    description: "Use the open Specflow method to turn intent into software through structured planning and iterative execution with software agents."
    image: "https://www.specflow.com/assets/og-image.png"
    card-style: "summary_large_image"
  navbar:
    background: primary
    logo: assets/specflow_light.svg
    logo-alt: "Specflow"
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: why-plan-first.qmd
        text: Why Plan First
      - href: about.qmd
        text: About
      - href: getting-started.qmd
        text: Getting Started
      - text: Learn
        menu:
          - href: examples/index.qmd
            text: Project Examples
          - href: videos.qmd
            text: Videos
          - href: reference/index.qmd
            text: Reference
    right:
      - icon: github
        href: https://github.com/specstoryai/specflow
        aria-label: GitHub
  page-footer:
    center: |
      &copy; 2025 <a href="https://www.specstory.com" target="_blank">SpecStory</a> - Intent is the new source code

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    anchor-sections: true
    smooth-scroll: true
    mermaid:
      theme: default
    include-in-header:
      - text: |
          <script>
            window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };
          </script>
          <script defer src="/_vercel/insights/script.js"></script>



