project:
  type: website

website:
  title: "SpecFlow"
  description: "A structured pattern for prompting AI agents to build software - orchestrating intent, step-by-step, from what we want to what gets built."
  site-url: "https://specflow.ai"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: why-plan-first.qmd
        text: Why Plan First
      - href: getting-started.qmd
        text: Getting Started
      - text: Learn
        menu:
          - href: examples/index.qmd
            text: Examples
          - href: reference/index.qmd
            text: Reference
  page-footer:
    center: |
      &copy; 2024 SpecFlow - Building software with structured intent

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    anchor-sections: true
    smooth-scroll: true
    mermaid:
      theme: default



