project:
  type: website

website:
  title: " "
  description: "A structured pattern for prompting AI agents to build software - orchestrating intent, step-by-step, from what we want to what gets built."
  site-url: "https://specflow.ai"
  navbar:
    background: primary
    logo: assets/specflow_light.svg
    logo-alt: "Specflow"
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: why-plan-first.qmd
        text: Why Plan First
      - href: about.qmd
        text: About
      - href: getting-started.qmd
        text: Getting Started
      - text: Learn
        menu:
          - href: examples/index.qmd
            text: Project Examples
          - href: videos.qmd
            text: Videos
          - href: reference/index.qmd
            text: Reference
    right:
      - icon: github
        href: https://github.com/specstoryai/specflow
        aria-label: GitHub
  page-footer:
    center: |
      &copy; 2025 SpecStory - Intent is the new source code

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    anchor-sections: true
    smooth-scroll: true
    mermaid:
      theme: default



